import type { ProductTypeConfig } from "../types";

export const productTypes: ProductTypeConfig = {
  types: [
    {
      type: "electronics",
      label: "Electronics",
      labelPlural: "Electronics",
      verb: "Purchase",
      verbPastTense: "Purchased",
      priceLabel: "Price",
      showPrice: true,
      additionalFields: ["brand", "warranty"],
      categories: [
        "Headphones",
        "Speakers",
        "Cameras",
        "Computers",
        "Phones",
        "Accessories",
      ],
      pageTitle: "Electronics",
      pageDescription: "Shop the latest electronics and gadgets",
    },
    {
      type: "clothing",
      label: "Clothing",
      labelPlural: "Clothing",
      verb: "Purchase",
      verbPastTense: "Purchased",
      priceLabel: "Price",
      showPrice: true,
      additionalFields: ["size", "color"],
      categories: [
        "Men's",
        "Women's",
        "Kids",
        "Shoes",
        "Accessories",
      ],
      pageTitle: "Clothing",
      pageDescription: "Discover fashion and apparel for everyone",
    },
    {
      type: "home",
      label: "Home & Garden",
      labelPlural: "Home & Garden",
      verb: "Purchase",
      verbPastTense: "Purchased",
      priceLabel: "Price",
      showPrice: true,
      additionalFields: ["dimensions"],
      categories: [
        "Furniture",
        "Decor",
        "Kitchen",
        "Garden",
        "Bedding",
      ],
      pageTitle: "Home & Garden",
      pageDescription: "Everything for your home and garden",
    },
  ],
};
